name: cypress-test
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
         
    steps:
      - uses: actions/checkout@v3
        with:
          ref: wf-test

      - name: Install Dependencies
        run: npm install
    
       
